In [1]:
print('hello world')



hello world


### Array Operation

In [8]:
2**32

4294967296

In [9]:
2**64

18446744073709551616

In [10]:
import numpy as np

In [11]:
num = np.array([56,23,11,6,42,38,64])

In [12]:
print(num)

[56 23 11  6 42 38 64]


In [13]:
num

array([56, 23, 11,  6, 42, 38, 64])

In [14]:
num.dtype

dtype('int32')

In [15]:
num.size

7

In [16]:
num[3]

6

In [18]:
num[5]=94
num

array([56, 23, 11,  6, 42, 94, 64])

In [20]:
num

array([56, 23, 11,  6, 42, 94, 64])

In [21]:
num=np.array([2,3,4,5,6,8.7,6,1])

In [22]:
num.dtype


dtype('float64')

In [24]:
num=np.array([2,3,4,5,6,7,8,False])
num

array([2, 3, 4, 5, 6, 7, 8, 0])

In [26]:
num=np.array([2,3,4,5,6,'hello',5,8,9])

In [27]:
num

array(['2', '3', '4', '5', '6', 'hello', '5', '8', '9'], dtype='<U11')

In [31]:
city=np.array(['पुणे ', 'मुंबई ', 'नागपूर ','नाशिक '])

In [32]:
city

array(['पुणे ', 'मुंबई ', 'नागपूर ', 'नाशिक '], dtype='<U7')

In [33]:
city[3]

'नाशिक '

In [34]:
city[2]*5

'नागपूर नागपूर नागपूर नागपूर नागपूर '

In [36]:
num=np.array([2,3,4,5,6,8.7,6,1])

In [37]:
num.max()

8.7

In [38]:
num.sum()

35.7

In [39]:
num.std()

2.328592654373023

In [41]:
x=[56,23,11,6,42,38,64]
x*2

[56, 23, 11, 6, 42, 38, 64, 56, 23, 11, 6, 42, 38, 64]

In [43]:
num*2

array([ 4. ,  6. ,  8. , 10. , 12. , 17.4, 12. ,  2. ])

In [44]:
num/10

array([0.2 , 0.3 , 0.4 , 0.5 , 0.6 , 0.87, 0.6 , 0.1 ])

In [45]:
num-20

array([-18. , -17. , -16. , -15. , -14. , -11.3, -14. , -19. ])

In [46]:
num>20

array([False, False, False, False, False, False, False, False])

In [47]:
num<20

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [51]:
56 in x

True

In [52]:
100 not in x

True

In [53]:
list(range(1,20))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [55]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [56]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [57]:
list(range(10,0,-2))

[10, 8, 6, 4, 2]

In [58]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [60]:
np.arange(30,0,-2)

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [61]:
np.arange(1,30,.35)

array([ 1.  ,  1.35,  1.7 ,  2.05,  2.4 ,  2.75,  3.1 ,  3.45,  3.8 ,
        4.15,  4.5 ,  4.85,  5.2 ,  5.55,  5.9 ,  6.25,  6.6 ,  6.95,
        7.3 ,  7.65,  8.  ,  8.35,  8.7 ,  9.05,  9.4 ,  9.75, 10.1 ,
       10.45, 10.8 , 11.15, 11.5 , 11.85, 12.2 , 12.55, 12.9 , 13.25,
       13.6 , 13.95, 14.3 , 14.65, 15.  , 15.35, 15.7 , 16.05, 16.4 ,
       16.75, 17.1 , 17.45, 17.8 , 18.15, 18.5 , 18.85, 19.2 , 19.55,
       19.9 , 20.25, 20.6 , 20.95, 21.3 , 21.65, 22.  , 22.35, 22.7 ,
       23.05, 23.4 , 23.75, 24.1 , 24.45, 24.8 , 25.15, 25.5 , 25.85,
       26.2 , 26.55, 26.9 , 27.25, 27.6 , 27.95, 28.3 , 28.65, 29.  ,
       29.35, 29.7 ])

In [63]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
np.ones(14)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
np.empty(10)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [67]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [68]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [69]:
x=np.array([[4,5,6],[8,9,12]])

In [70]:
x

array([[ 4,  5,  6],
       [ 8,  9, 12]])

In [71]:
x.shape

(2, 3)

In [72]:
x.size

6

In [73]:
x.ndim

2

In [74]:
x[1][2]

12

In [75]:
x.reshape(3,2)

array([[ 4,  5],
       [ 6,  8],
       [ 9, 12]])

In [76]:
x.reshape(6,1)

array([[ 4],
       [ 5],
       [ 6],
       [ 8],
       [ 9],
       [12]])

In [79]:
x.reshape(-1,2)

array([[ 4,  5],
       [ 6,  8],
       [ 9, 12]])

In [80]:
x.flatten()

array([ 4,  5,  6,  8,  9, 12])

In [81]:
import pandas as pd

In [83]:
s = pd.Series([2,3,4,5,6,8,9])

In [84]:
s

0    2
1    3
2    4
3    5
4    6
5    8
6    9
dtype: int64

In [85]:
s[4]

6

In [86]:
s[4]=90

In [87]:
s

0     2
1     3
2     4
3     5
4    90
5     8
6     9
dtype: int64

In [90]:
s = pd.Series([2,3,4,5,6,8,9], index=range(100,107))

In [91]:
s

100    2
101    3
102    4
103    5
104    6
105    8
106    9
dtype: int64

In [92]:
s[104]

6

In [93]:
s.dtype

dtype('int64')

In [94]:
s.size

7

### Data Frame Operations

In [95]:
x=pd.Series([1,2,3,4])
y=pd.Series(['keshu','vishu','shivu','himi'])
z=pd.Series([54,22,56,23])

In [96]:
df=pd.DataFrame({'roll':x,'name':y,'marks':z})


In [103]:
df

roll   name  marks
0     1  keshu     54
1     2  vishu     22
2     3  shivu     56
3     4   himi     23

In [104]:
df.shape

(4, 3)

In [106]:
df.columns

Index(['roll', 'name', 'marks'], dtype='object')

In [107]:
df.size

12

In [108]:
df.T

0      1      2     3
roll       1      2      3     4
name   keshu  vishu  shivu  himi
marks     54     22     56    23

In [109]:
list(s)

[2, 3, 4, 5, 6, 8, 9]

In [110]:
tuple(s)

(2, 3, 4, 5, 6, 8, 9)

In [111]:
set(s)

{2, 3, 4, 5, 6, 8, 9}

In [112]:
s.values

array([2, 3, 4, 5, 6, 8, 9], dtype=int64)

In [113]:
df.values

array([[1, 'keshu', 54],
       [2, 'vishu', 22],
       [3, 'shivu', 56],
       [4, 'himi', 23]], dtype=object)

In [114]:
dict(df)

{'roll': 0    1
 1    2
 2    3
 3    4
 Name: roll, dtype: int64,
 'name': 0    keshu
 1    vishu
 2    shivu
 3     himi
 Name: name, dtype: object,
 'marks': 0    54
 1    22
 2    56
 3    23
 Name: marks, dtype: int64}

### Statistics

In [115]:
y=np.array([2,3,5,6,4,8])

In [116]:
x.mean()

2.5

In [117]:
y.mean()

4.666666666666667

In [118]:
import os
os.getcwd()

'C:\\Users\\lenovo'